# Generated by Django 4.0.2 on 2022-03-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AQG', '0003_osquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilesAdmin',
            new_name='Filess',
        ),
    ]
