# Generated by Django 4.0.2 on 2022-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQG', '0004_rename_filesadmin_filess'),
    ]

    operations = [
        migrations.AddField(
            model_name='filess',
            name='scan_link',
            field=models.URLField(default='/downloadfromhere', max_length=1000),
        ),
    ]
