# Generated by Django 4.0.2 on 2022-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQG', '0005_filess_scan_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filess',
            name='scan_link',
            field=models.URLField(default='http://127.0.0.1:8000/downloadfromhere', max_length=1000),
        ),
    ]
