# Generated by Django 4.0.2 on 2022-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQG', '0006_alter_filess_scan_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(choices=[('dbms', 'Dbms'), ('es', 'Embedded System'), ('os', 'operating System')], default='Dbms', max_length=20)),
                ('Pdf_file', models.FileField(upload_to='')),
                ('Pdf_Name', models.CharField(max_length=100)),
                ('Scan_Link', models.URLField(default='http://127.0.0.1:8000/ocr_signal', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=1000000)),
                ('mark', models.IntegerField(default=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Dbms',
        ),
        migrations.RenameModel(
            old_name='Osquestion',
            new_name='Es',
        ),
        migrations.DeleteModel(
            name='Filess',
        ),
    ]
